### PR TITLE
reviewers is part of the options array

### PR DESCRIPTION
**Pull request by joestewart**

### CODE REVIEW

**Comment by aaronbauman** [comment]
LGTM, but can you please file this against https://github.com/pantheon-systems/terminus-clu-plugin ?
This project is a fork that's no longer supported, and I'm not sure the easiest way to change the merge target.

**Comment by joestewart** [comment]
Thanks Aaron I didn't realize that and will take a look.

Does that mean the danielbachhuber/composer-lock-updater README needs updating too?

**Comment by joestewart** [comment]
there was a typo anyway :)

Replaced by
https://github.com/pantheon-systems/terminus-clu-plugin/pull/7

**Comment by aaronbauman** [comment]
danielbachhuber/composer-lock-updater is still maintained separately, because it can be used outside a pantheon / terminus environment.

**Comment by joestewart** [comment]
Sorry I wasn't more clear the danielbachhuber/composer-lock-updater README has the text "For example, to add support for a Bitbucket-Pantheon project using Terminus Bitbucket Plugin..."

**Comment by aaronbauman** [comment]
Oh, I see.
Yeah, that should be updated.

I also updated the README for this project to point to the pantheon version.

**Pull request closed without merging**
